In [19]:
import pandas as pd

df = pd.read_csv('CIA2_Misclassified_Comments_Log.csv')
df.head(2)

,Variation,Embedding,Classifier,True_Label,Predicted_Label,Comment_Text
0,var_1_all_preprocessing,TFIDF,Naive_Bayes,2,0,Priya mapping the maze on cardboard?? That's a...
1,var_1_all_preprocessing,TFIDF,Naive_Bayes,2,0,Tyler not quitting with a sprained ankle bro I...

In [20]:
df['Classifier'].value_counts()

Classifier
Naive_Bayes      4399
MLP_NeuralNet    3384
XGBoost          3108
LinearSVC        2609
Name: count, dtype: int64

In [21]:
filter_df = df[df['Embedding'] == 'ROBERTA']
filter_df = filter_df[filter_df['Classifier'] == 'LinearSVC']
filter_df = filter_df[['Comment_Text','Predicted_Label','True_Label','Variation']]
filter_df.to_csv('ROBERTA_LinearSVC_Misclassified_Comments.csv', index=False)

In [23]:
# filter comments where true label is 1 but predicted label is 0
filter_df[(filter_df['True_Label'] == 2) & (filter_df['Predicted_Label'] == 0)]

,Comment_Text,Predicted_Label,True_Label,Variation
2209,Tyler not quitting with a sprained ankle bro I...,0,2,var_1_all_preprocessing
2210,She said she's donating half to her family I'm...,0,2,var_1_all_preprocessing
2212,The overnight maze rearrangement twist was CRA...,0,2,var_1_all_preprocessing
2234,not gonna lie tHE TWIST emoji_exploding_head n...,0,2,var_1_all_preprocessing
2235,fr fr the scale of this maze is genuinely hard...,0,2,var_1_all_preprocessing
...,...,...,...,...
13112,i can't believe priya saying she'll donate hal...,0,2,var_5_all_lowercased
13117,not gonna lie the twist emoji_exploding_head n...,0,2,var_5_all_lowercased
13118,fr fr the scale of this maze is genuinely hard...,0,2,var_5_all_lowercased
13119,other channels attempt this format but this is...,0,2,var_5_all_lowercased
13120,can we all agree that i can't believe jake's e...,0,2,var_5_all_lowercased